language: csharp
mono:
- beta

install: curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh
  | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade

before_script:
    - curl -fsSkL https://gist.github.com/ianbattersby/c3399aa8cd9e2a6f8afa/raw > travis.sh && source ./travis.sh
    - evm list
    - emacs --version
    - cask install
    - mkdir omnisharp-roslyn
    - cd omnisharp-roslyn
    - wget $(curl -s https://api.github.com/repos/omnisharp/omnisharp-roslyn/releases/latest | grep browser_download_url | awk '{ print $2 }' | sed s/\"//g | sed s/,//g)
    - tar xzvf omnisharp.tar.gz
    - cd ..
    - mono --version

script:
    ./run-entire-travis-build.sh

notifications:
    webhooks:
        urls:
          - https://webhooks.gitter.im/e/5ad7b48d1cea3eb74221
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false
