language: generic
sudo: required
dist: trusty

install:
    - sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
    - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
    - sudo apt-get -qq update
    - sudo apt-get install -y dotnet-dev-1.0.0-rc2-002543
    - dotnet --version

before_script:
    - curl -fsSkL https://gist.github.com/ianbattersby/c3399aa8cd9e2a6f8afa/raw > travis.sh && source ./travis.sh
    - evm list
    - emacs --version
    - cask install
    - cd travis-stuff
    - ./install-omnisharp-roslyn.sh
    - cd ..

script:
    ./run-entire-travis-build.sh

notifications:
    webhooks:
        urls:
          - https://webhooks.gitter.im/e/5ad7b48d1cea3eb74221
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false
