(source melpa)
(source gnu)

(package-file "omnisharp.el")

(development
 (depends-on "cl-lib")
 (depends-on "prodigy")
 (depends-on "ecukes")
 (depends-on "ert-async")
 (depends-on "noflet")
 (depends-on "s")
 (depends-on "ert-runner")
 (depends-on "ert-runner")
 (depends-on "el-mock")
 (depends-on "json")
 (depends-on "dash")
 (depends-on "popup")
 (depends-on "auto-complete")
 (depends-on "flycheck")
 (depends-on "csharp-mode")
 (depends-on "evil"))
