name: Run tests

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  run-melpa-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: docker-compose build
      run: docker-compose build

    - name: docker-compose run --rm melpa-tests
      run: docker-compose run --rm melpa-tests

  run-regular-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: omnisharp server cache dir
      uses: actions/cache@v2
      with:
        path: ~/.emacs.d/.cache/omnisharp/server/
        key: ${{ runner.os }}-emacs-d-cache-omnisharp-server

    - name: docker-compose build
      run: docker-compose build

    - name: docker-compose run --rm regular-tests
      run: docker-compose run --rm regular-tests
